services:
  mysql:
    image: mysql:8.4
    container_name: inventory
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - inv_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: inventory_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8801:80"
    depends_on:
      - mysql

volumes:
  inv_mysql_data:
